#!/bin/sh
#SBATCH --partition=slurm_shortgpu
#SBATCH --nodes=2
#SBATCH --tasks=2
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=40
#SBATCH -e job_err
#SBATCH -o job_out
###SBATCH --gres=gpu:1 # not needed for OpenMP

##./GALS_Advection 

mpiexec -np 2 ./GALS_Advection

mv job_out ggg.out
mv job_err ggg.err
