#!/bin/sh
#SBATCH --partition=slurm_shortgpu
#SBATCH --nodes=1
#SBATCH --tasks=1
#SBATCH --ntasks-per-node=1
#SBATCH --cpus-per-task=40
#SBATCH -e job_err
#SBATCH -o job_out
###SBATCH --gres=gpu:1 # not needed for OpenMP


#for((i=1; i<21;i++))
#do
##    ./problem3 $i
#done

##./GALS_Advection 

mpiexec -np 1 ./GALS_Advection

mv job_out ggg.out
mv job_err ggg.err
